#!/bin/bash

#PBS -r n
#PBS -l walltime=20:00:00
#PBS -l procs=20
#PBS -l pmem=700m
#PBS -m bea
#PBS -M theajobreports@gmail.com

cd /home/tva4/scripts
echo "prog started at: `date`"
read_fasta -i /global/scratch/tva4/Illumina_Feb8_2013/readsTrimQ-FilterN-FilterL-fasta/BAC001_QCed_1.fasta,/global/scratch/tva4/Illumina_Feb8_2013/readsTrimQ-FilterN-FilterL-fasta/BAC001_QCed_2.fasta | order_pairs | write_fasta -o /global/scratch/tva4/Illumina_Feb8_2013/readsTrimQ-FilterN-FilterL-fasta/paired/BAC001_QCed_paired.fasta -x
echo "prog finished at: `date`"
